# Generated by Django 5.2.3 on 2025-07-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_remove_userprofile_user_points_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='linkedin_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='policy_url',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_id',
            field=models.CharField(max_length=200),
        ),
    ]
