# Generated by Django 5.2.3 on 2025-07-06 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_company_linkedin_id_alter_company_policy_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country_code',
            field=models.CharField(default='DE', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_list',
            field=models.FileField(upload_to='employee_lists/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'xlsx'])]),
        ),
    ]
