# Generated by Django 5.2.3 on 2025-07-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_company_country_code_alter_company_employee_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country_code',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
