# Generated by Django 5.2.3 on 2025-07-06 12:46

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_company_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_link',
            field=autoslug.fields.AutoSlugField(default=2, editable=False, populate_from='my_slug', unique=True),
            preserve_default=False,
        ),
    ]
