# Generated by Django 5.2.3 on 2025-07-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_company_company_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='title',
            new_name='company_name',
        ),
    ]
