# Generated by Django 5.2.3 on 2025-07-06 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_title_company_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='vat_id',
            new_name='VAT_ID',
        ),
    ]
