# Generated by Django 5.2.3 on 2025-07-06 15:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rename_linkedin_id_company_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_link',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='company_name', unique=True),
        ),
    ]
