# Generated by Django 5.2.3 on 2025-07-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_company_company_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='linkedin_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='policy_url',
            field=models.URLField(),
        ),
    ]
