# Generated by Django 5.2.3 on 2025-07-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_company_linkedin_url_alter_company_policy_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='policy_rag_file',
            field=models.FileField(blank=True, null=True, upload_to='vectored_policy/'),
        ),
    ]
