# Generated by Django 5.2.3 on 2025-07-07 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_company_policy_rag_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='policy_rag_file',
        ),
    ]
